### ISSUE TITLE
Transactions ordered by expiration instead of created at

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#8]
Use expiration or improve the mongodb plugin.

Created At is incorrect as it will use the creation of the mongodb entry instead of the current transaction.

**Comment by ghoti143** [comment]
How about joining to the Block collection when querying the Transactions and grab the timestamp from the Block record and use that value instead of Created At?

**Comment by kesar** [comment]
Yeah, that could work as well 👍 great idea. I was also thinking to tweak the mongodb plugin to store proper data in Transactions

**Comment by ghoti143** [comment]
Yeah -- tweaking mongodb could work as well, but if the performance of doing a mongo "join" is not too detrimental, it might be better to go this route because it would reduce the amount of duplicate data stored in the database (since all transactions in a block will have the same timestamp...correct?).  When eosio gets up into the 10000's of transaction per second realm, that's a significant amount of data that won't need to be duplicated...

If we want to go this direction, I've opened an issue in the API project: https://github.com/EOSEssentials/EOSTracker-API/issues/8

**Comment by kesar** [comment]
done
